name: Build, Test & Quality Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  quality:
    name: Code Quality & Package Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js environment (v${{ matrix.node-version }})
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Biome.js formatter and linter
        uses: biomejs/setup-biome@v2
        with:
          version: latest

      - name: Install project dependencies
        run: npm ci

      - name: Verify code style and formatting (Biome)
        run: |
          npm run lint
          npm run format

      - name: Verify TypeScript types
        run: npm run check-types

      - name: Run unit and integration tests
        run: npm test

      - name: Build production package
        run: npm run build
