name: NPM Package Release

on:
  release:
    types: [published]

jobs:
  publish:
    name: Build & Publish to NPM Registry

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    permissions:
      contents: read # Allow reading repository contents
      id-token: write # Allow writing an OIDC token for authentication

    steps:
      - uses: actions/checkout@v4 # Check out the repository code

      - name: Set up Node.js environment (v${{ matrix.node-version }})
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://registry.npmjs.org"
          cache: "npm"

      - name: Install project dependencies
        run: npm ci

      - name: Build production package
        run: npm run build --if-present

      - name: Publish package to NPM Registry
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
